# Generated by Django 4.2.4 on 2023-12-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shared_files',
            field=models.ManyToManyField(blank=True, to='file_share.userprofile'),
        ),
    ]
